# Generated by Django 6.0.1 on 2026-07-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Is_verified',
            new_name='is_verified',
        ),
    ]
