# Generated by Django 6.0.1 on 2026-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profileimage_profile_profileimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.BinaryField(default=None),
        ),
    ]
