# Generated by Django 6.0.1 on 2026-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='google_map_link',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
