# Generated by Django 6.0.1 on 2026-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_furnishing_property_google_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.BinaryField(),
        ),
    ]
