# Generated by Django 6.0.1 on 2026-07-19 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_address_profile_address_and_more'),
        ('properties', '0004_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.profile'),
        ),
    ]
