# Generated by Django 6.0.1 on 2026-07-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
